backend:
  name: git-gateway #test-repo #git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets
collections:
  - label: "Content"
    name: "content"
    editor:
      preview: false
    files:
      - name: forward
        label: Forward
        file: md/forward.md
        description: "Edit tips here"
        fields:
          - { label: Title, name: title, widget: hidden }
          - { label: Body, name: body, widget: markdown }
      - name: screenplay
        label: Screenplay
        file: md/screnplay.md
        description: "Explain how to edit here"
        fields:
          - { label: Title, name: title, widget: hidden }
          - { label: Body, name: body, widget: markdown }