backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets
collections:
  - name: intro
    label: Intro
    folder: md
    create: false
    fields:
      - { name: path, label: Path }
      - {label: Title, name: title, widget: hidden}
      - {label: Body, name: body, widget: markdown}
  - name: screenplay
    label: Screenplay
    folder: md
    create: false
    fields:
      - { name: path, label: Path }
      - {label: Title, name: title, widget: hidden}
      - {label: Body, name: body, widget: markdown}