backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets
collections:
  - name: intro
    label: Intro
    folder: md
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }